=== junxito/EjerciciosLMSG/EjerciciosLMSG/xml-dtd-examen1102/examen1102.dtd
<!ELEMENT alimentos_dieta (alimentos_permitidos, alimentos_prohibidos)>
<!ELEMENT alimentos_permitidos (permitidos)>
<!ELEMENT permitidos (#PCDATA | comida | alimento | best_timing)*>
<!ENTITY % informacion_comida "nombre CDATA #REQUIRED
                              tiempo CDATA #FIXED 'noche'
                              plato NMTOKEN #IMPLIED">
<!ELEMENT comida EMPTY>
<!ATTLIST comida %informacion_comida;>
<!ELEMENT alimento EMPTY>
<!ATTLIST alimento %informacion_comida;>
<!ELEMENT best_timing EMPTY>
<!ATTLIST best_timing %informacion_comida;>
<!ELEMENT alimentos_prohibidos (prohibidos? | momento?)*>
<!ELEMENT prohibidos (fruta | precocinado)*>
<!ELEMENT fruta EMPTY>
<!ATTLIST fruta nombre CDATA #REQUIRED
                plato IDREF #REQUIRED>
<!ELEMENT precocinado EMPTY>
<!ATTLIST precocinado nombre CDATA #REQUIRED
                      plato IDREF #REQUIRED
                      tiempo IDREFS #IMPLIED>
<!ELEMENT momento EMPTY>
<!ATTLIST momento plato ID #IMPLIED
                  tiempo ID #IMPLIED>

=== junxito/EjerciciosLMSG/EjerciciosLMSG/xml-dtd-examen1102/examen1102.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alimentos_dieta SYSTEM "examen1102.dtd" []>

<alimentos_dieta>
    <alimentos_permitidos>
        <permitidos>
            <comida nombre= "bacalao con ensalada y ajos fritos" tiempo= "noche" plato= "principal"/>
            <alimento nombre= "melón con jamón" tiempo= "noche" plato= "principal"/>
            arroz sazonado al estilo oriental con estofado de curry al estilo japonés
            <best_timing nombre= "helado" tiempo= "noche"/>
        </permitidos>
    </alimentos_permitidos>
    <alimentos_prohibidos>
        <prohibidos>
            <fruta nombre= "melón" plato= "postre"/>
            <fruta nombre= "sandía" plato= "postre"/>
            <precocinado nombre= "pizza" plato= "principal" tiempo= "mediodia noche"/>
        </prohibidos>
        <momento tiempo= "mediodia" plato= "segundo"/>
        <momento tiempo= "maniana" plato= "principal"/>
        <momento tiempo= "noche" plato= "postre"/>
    </alimentos_prohibidos>
</alimentos_dieta>
