=== junxito/EjerciciosLMSG/EjerciciosLMSG/xml-dtd-variados/prueba_examen_dragonball.dtd
<!ELEMENT personajes (humanos? | aliens?)*>
    <!ELEMENT humanos (protagonistas)>
    <!ELEMENT protagonistas (saiyans, ordinarios, luchadores, extras, mejor_personaje)>
    <!ELEMENT saiyans (saiyan)*>
    <!ELEMENT saiyan EMPTY>
    <!ATTLIST saiyan nombre ID #REQUIRED>
    <!ATTLIST saiyan alias CDATA #IMPLIED>
    <!ATTLIST saiyan raza NMTOKEN #IMPLIED>
    <!ATTLIST saiyan pelo (rojo | amarillo |azul ) #REQUIRED>
    <!ELEMENT ordinarios (ordinario)>
    <!ELEMENT ordinario EMPTY>
    <!ATTLIST ordinario nombre  CDATA #REQUIRED>
    <!ELEMENT luchadores (#PCDATA)>
    <!ELEMENT extras (#PCDATA)>
    <!ELEMENT mejor_personaje EMPTY>
    <!ATTLIST mejor_personaje nombre IDREFS #REQUIRED>
    <!ELEMENT aliens (antagonistas)>
    <!ELEMENT antagonistas (#PCDATA | origen | enemigos)*>
    <!ELEMENT origen (planeta+)>
    <!ELEMENT planeta EMPTY>
    <!ATTLIST planeta nombre ID #REQUIRED
                    proveniencia NMTOKEN #IMPLIED>
    <!ELEMENT enemigos (enemigo+)>
    <!ELEMENT enemigo EMPTY>
    <!ATTLIST enemigo nombre CDATA #REQUIRED
                    planeta IDREF #IMPLIED
                    estado CDATA #FIXED "no destruido">

=== junxito/EjerciciosLMSG/EjerciciosLMSG/xml-dtd-variados/prueba_examen_dragonball.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "prueba_examen_dragonball.dtd" []>

<personajes>
    <humanos>
        <protagonistas>
            <saiyans>
                <saiyan nombre= "goku" alias= "kakarot" raza= "humana" pelo= "rojo"/>
                <saiyan nombre= "vegetta" alias= "gruñón" pelo= "azul"/>
                <saiyan nombre= "gohan" pelo= "amarillo"/> 
                <saiyan nombre= "trunks" pelo= "amarillo"/>              
            </saiyans>
            <ordinarios>
                <ordinario nombre= "bulma"/>
            </ordinarios>
            <luchadores>krillin</luchadores>
            <extras>satan</extras>
            <mejor_personaje nombre= "gohan trunks"/>
           
            
        </protagonistas>
    </humanos>
    <aliens>
        <antagonistas>
            <origen>
                <planeta nombre= "tierra" proveniencia= "bio"/>
                <planeta nombre= "namek" proveniencia= "nam"/>
            </origen>
            dioses
            <enemigos>
                <enemigo nombre= "cell" planeta= "tierra"/>
                <enemigo nombre= "freezer" planeta= "namek"/>
            </enemigos>
        </antagonistas >
    </aliens>
</personajes>
